# The generated code will be written to this file
dest = 'lib/DeepTest.sol'
# Directory to look for Solidity compiler artifacts (forge uses 'out' by default)
artifacts = 'out'
# forge-deep will generate functions for all user-defined value types, enums, structs, and array types used in these contracts
contracts = [
    # NOTE: The definition order matters 
    'src/state/BlobStorage.sol',
    'src/proving/Compliance.sol',
    'src/proving/Logic.sol',
    'src/libs/AppData.sol',
    'src/Types.sol',
]
# forge-deep will generate functions for the following types, which may be defined outside of the contracts listed above
types = []
